// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: card.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_card_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_card_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_card_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_card_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_card_2eproto;
class card;
struct cardDefaultTypeInternal;
extern cardDefaultTypeInternal _card_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::card* Arena::CreateMaybeMessage<::card>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class card final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:card) */ {
 public:
  inline card() : card(nullptr) {}
  ~card() override;
  explicit constexpr card(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  card(const card& from);
  card(card&& from) noexcept
    : card() {
    *this = ::std::move(from);
  }

  inline card& operator=(const card& from) {
    CopyFrom(from);
    return *this;
  }
  inline card& operator=(card&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const card& default_instance() {
    return *internal_default_instance();
  }
  static inline const card* internal_default_instance() {
    return reinterpret_cast<const card*>(
               &_card_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(card& a, card& b) {
    a.Swap(&b);
  }
  inline void Swap(card* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(card* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  card* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<card>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const card& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const card& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(card* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "card";
  }
  protected:
  explicit card(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLegalAdressFieldNumber = 2,
    kTitleFieldNumber = 3,
    kOccupationFieldNumber = 4,
    kYearOfFoundationFieldNumber = 1,
    kForeignEconomicActivityFieldNumber = 5,
  };
  // required string legal_adress = 2;
  bool has_legal_adress() const;
  private:
  bool _internal_has_legal_adress() const;
  public:
  void clear_legal_adress();
  const std::string& legal_adress() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_legal_adress(ArgT0&& arg0, ArgT... args);
  std::string* mutable_legal_adress();
  PROTOBUF_NODISCARD std::string* release_legal_adress();
  void set_allocated_legal_adress(std::string* legal_adress);
  private:
  const std::string& _internal_legal_adress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_legal_adress(const std::string& value);
  std::string* _internal_mutable_legal_adress();
  public:

  // required string title = 3;
  bool has_title() const;
  private:
  bool _internal_has_title() const;
  public:
  void clear_title();
  const std::string& title() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_title(ArgT0&& arg0, ArgT... args);
  std::string* mutable_title();
  PROTOBUF_NODISCARD std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // optional string occupation = 4;
  bool has_occupation() const;
  private:
  bool _internal_has_occupation() const;
  public:
  void clear_occupation();
  const std::string& occupation() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_occupation(ArgT0&& arg0, ArgT... args);
  std::string* mutable_occupation();
  PROTOBUF_NODISCARD std::string* release_occupation();
  void set_allocated_occupation(std::string* occupation);
  private:
  const std::string& _internal_occupation() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_occupation(const std::string& value);
  std::string* _internal_mutable_occupation();
  public:

  // required int32 year_of_foundation = 1;
  bool has_year_of_foundation() const;
  private:
  bool _internal_has_year_of_foundation() const;
  public:
  void clear_year_of_foundation();
  int32_t year_of_foundation() const;
  void set_year_of_foundation(int32_t value);
  private:
  int32_t _internal_year_of_foundation() const;
  void _internal_set_year_of_foundation(int32_t value);
  public:

  // optional bool foreign_economic_activity = 5;
  bool has_foreign_economic_activity() const;
  private:
  bool _internal_has_foreign_economic_activity() const;
  public:
  void clear_foreign_economic_activity();
  bool foreign_economic_activity() const;
  void set_foreign_economic_activity(bool value);
  private:
  bool _internal_foreign_economic_activity() const;
  void _internal_set_foreign_economic_activity(bool value);
  public:

  // @@protoc_insertion_point(class_scope:card)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr legal_adress_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr occupation_;
  int32_t year_of_foundation_;
  bool foreign_economic_activity_;
  friend struct ::TableStruct_card_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// card

// required int32 year_of_foundation = 1;
inline bool card::_internal_has_year_of_foundation() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool card::has_year_of_foundation() const {
  return _internal_has_year_of_foundation();
}
inline void card::clear_year_of_foundation() {
  year_of_foundation_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline int32_t card::_internal_year_of_foundation() const {
  return year_of_foundation_;
}
inline int32_t card::year_of_foundation() const {
  // @@protoc_insertion_point(field_get:card.year_of_foundation)
  return _internal_year_of_foundation();
}
inline void card::_internal_set_year_of_foundation(int32_t value) {
  _has_bits_[0] |= 0x00000008u;
  year_of_foundation_ = value;
}
inline void card::set_year_of_foundation(int32_t value) {
  _internal_set_year_of_foundation(value);
  // @@protoc_insertion_point(field_set:card.year_of_foundation)
}

// required string legal_adress = 2;
inline bool card::_internal_has_legal_adress() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool card::has_legal_adress() const {
  return _internal_has_legal_adress();
}
inline void card::clear_legal_adress() {
  legal_adress_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& card::legal_adress() const {
  // @@protoc_insertion_point(field_get:card.legal_adress)
  return _internal_legal_adress();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void card::set_legal_adress(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 legal_adress_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:card.legal_adress)
}
inline std::string* card::mutable_legal_adress() {
  std::string* _s = _internal_mutable_legal_adress();
  // @@protoc_insertion_point(field_mutable:card.legal_adress)
  return _s;
}
inline const std::string& card::_internal_legal_adress() const {
  return legal_adress_.Get();
}
inline void card::_internal_set_legal_adress(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  legal_adress_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* card::_internal_mutable_legal_adress() {
  _has_bits_[0] |= 0x00000001u;
  return legal_adress_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* card::release_legal_adress() {
  // @@protoc_insertion_point(field_release:card.legal_adress)
  if (!_internal_has_legal_adress()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = legal_adress_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (legal_adress_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    legal_adress_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void card::set_allocated_legal_adress(std::string* legal_adress) {
  if (legal_adress != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  legal_adress_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), legal_adress,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (legal_adress_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    legal_adress_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:card.legal_adress)
}

// required string title = 3;
inline bool card::_internal_has_title() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool card::has_title() const {
  return _internal_has_title();
}
inline void card::clear_title() {
  title_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& card::title() const {
  // @@protoc_insertion_point(field_get:card.title)
  return _internal_title();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void card::set_title(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 title_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:card.title)
}
inline std::string* card::mutable_title() {
  std::string* _s = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:card.title)
  return _s;
}
inline const std::string& card::_internal_title() const {
  return title_.Get();
}
inline void card::_internal_set_title(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  title_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* card::_internal_mutable_title() {
  _has_bits_[0] |= 0x00000002u;
  return title_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* card::release_title() {
  // @@protoc_insertion_point(field_release:card.title)
  if (!_internal_has_title()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = title_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (title_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    title_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void card::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  title_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), title,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (title_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    title_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:card.title)
}

// optional string occupation = 4;
inline bool card::_internal_has_occupation() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool card::has_occupation() const {
  return _internal_has_occupation();
}
inline void card::clear_occupation() {
  occupation_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& card::occupation() const {
  // @@protoc_insertion_point(field_get:card.occupation)
  return _internal_occupation();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void card::set_occupation(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 occupation_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:card.occupation)
}
inline std::string* card::mutable_occupation() {
  std::string* _s = _internal_mutable_occupation();
  // @@protoc_insertion_point(field_mutable:card.occupation)
  return _s;
}
inline const std::string& card::_internal_occupation() const {
  return occupation_.Get();
}
inline void card::_internal_set_occupation(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  occupation_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* card::_internal_mutable_occupation() {
  _has_bits_[0] |= 0x00000004u;
  return occupation_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* card::release_occupation() {
  // @@protoc_insertion_point(field_release:card.occupation)
  if (!_internal_has_occupation()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  auto* p = occupation_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (occupation_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    occupation_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void card::set_allocated_occupation(std::string* occupation) {
  if (occupation != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  occupation_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), occupation,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (occupation_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    occupation_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:card.occupation)
}

// optional bool foreign_economic_activity = 5;
inline bool card::_internal_has_foreign_economic_activity() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool card::has_foreign_economic_activity() const {
  return _internal_has_foreign_economic_activity();
}
inline void card::clear_foreign_economic_activity() {
  foreign_economic_activity_ = false;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool card::_internal_foreign_economic_activity() const {
  return foreign_economic_activity_;
}
inline bool card::foreign_economic_activity() const {
  // @@protoc_insertion_point(field_get:card.foreign_economic_activity)
  return _internal_foreign_economic_activity();
}
inline void card::_internal_set_foreign_economic_activity(bool value) {
  _has_bits_[0] |= 0x00000010u;
  foreign_economic_activity_ = value;
}
inline void card::set_foreign_economic_activity(bool value) {
  _internal_set_foreign_economic_activity(value);
  // @@protoc_insertion_point(field_set:card.foreign_economic_activity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_card_2eproto
